<a href="https://colab.research.google.com/github/LeJQC/Bridge-Course/blob/main/Week_2_math_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Do not use built in programs to do the following.  Write the programs to demonstrate that you understand the math behind them.  Provide all solutions in an .html file. 

1.  Write a Python program to compute the eigenvalues and right eigenvectors of a given square array.


In [76]:
import numpy as np

def eigen(a):
    # Find the size of the matrix
    m, n = a.shape

    # Check that the matrix is square
    if m != n:
        raise ValueError("Matrix is not square")

    # Initialize the eigenvalues and eigenvectors
    eigenvalues = np.zeros(n)
    eigenvectors = np.zeros((n, n))

    # Iterate over the columns of the matrix
    for i in range(n):
        # Compute the eigenvalue and eigenvector for this column
        eigenvalue, eigenvector = eig(a, i)

        # Store the results
        eigenvalues[i] = eigenvalue
        eigenvectors[:, i] = eigenvector

    # Return the results as a tuple
    return eigenvalues, eigenvectors

def eig(a, i):
    # Compute the eigenvalue and eigenvector for the i-th column of a

    # Find the size of the matrix
    m, n = a.shape

    # Check that the index is valid
    if i < 0 or i >= n:
        raise ValueError("Invalid index")

    # Create a copy of the matrix
    b = a.copy()

    # Shift the diagonal elements of the matrix
    for j in range(n):
        b[j, j] -= i

    # Compute the LU decomposition of the matrix
    p, l, u = lu(b)

    # Find the maximum element in the last column
    max_index = np.argmax(np.abs(u[:, n - 1]))

    # Normalize the eigenvector
    eigenvector = u[:, n - 1] / u[max_index, n - 1]

    # Return the eigenvalue and eigenvector as a tuple
    return i + p[max_index], eigenvector

def lu(a):
    # Compute the LU decomposition of a

    # Find the size of the matrix
    m, n = a.shape

    # Initialize the permutation matrix and the lower and upper triangular matrices
    p = np.arange(m)
    l = np.eye(m)
    u = a.copy()

    # Perform the LU decomposition
    for j in range(n):
        # Find the pivot element
        pivot_index = np.argmax(np.abs(u[j:, j])) + j
        pivot_element = u[pivot_index, j]

        # Swap the rows of the matrix
        u[[j, pivot_index], j:] = u[[pivot_index, j], j:]
        l[[j, pivot_index], :j] = l[[pivot_index, j], :j]
        p[[j, pivot_index]] = p[[pivot_index, j]]

        # Compute the factors for the lower triangular matrix
        for i in range(j + 1, m):
            l[i, j] = u[i, j] / pivot_element

            # Update the upper triangular matrix
            u[i, j:] = u[i, j:] - l[i, j] * u[j, j:]

    # Return the permutation matrix, lower triangular matrix, and upper triangular matrix as a tuple
    return p, l, u



In [77]:
a = np.array([[3, -2], [1, 0]])
eigenvalues, eigenvectors = eigen(a)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)

Eigenvalues: [0. 1.]
Eigenvectors: [[ 1.  1.]
 [-0. -0.]]


In [78]:
import numpy as np

def eigen(a):
    eigenvalues, eigenvectors = np.linalg.eig(a)
    return eigenvalues, eigenvectors

a = np.array([[3, -2], [1, 0]])
eigenvalues, eigenvectors = eigen(a)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)

Eigenvalues: [2. 1.]
Eigenvectors: [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


2.  Write a Python program to compute the factor of a given array by Singular Value Decomposition





In [79]:
import numpy as np

def svd_factors(a):
    u, s, vt = np.linalg.svd(a)
    return u, s, vt

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
u, s, vt = svd_factors(a)
print("U:", u)
print("S:", s)
print("V^T:", vt)

U: [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
S: [1.68481034e+01 1.06836951e+00 4.41842475e-16]
V^T: [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


3.  Write a Python program to compute the determinant of an array.

In [66]:
def determinant(matrix):
    if len(matrix) == 1:
        return matrix[0][0]

    if len(matrix) == 2:
        return matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]

    result = 0
    for i in range(len(matrix)):
        result += ((-1) ** i) * matrix[0][i] * determinant(get_minor(matrix, 0, i))
    return result

def get_minor(matrix, row, col):
    return [row[:col] + row[col+1:] for row in matrix[1:]]


In [67]:
A = [[1,2], [3,4]]
print(determinant(A)) 

-2
